### ISSUE TITLE
플레이어 전용 이미지 GUID 필요

### ISSUE THREAD

**Issue by Koesob0508** [Koesob0508/SOFe2022#20]
이제 플레이어는 용병이 아니니까 별도의 스프라이트를 쓸겁니다.
이 스프라이트 GUID를 몇 번으로 하면 좋을까요.

**Comment by DefineJH** [comment]
uint로 되어있으니까 음수는 못쓰고 Max로 씁시당
UInt32.MaxValue 로 ㄱㄱ

**Comment by Koesob0508** [comment]
> 
음 제가 알기론 이 resources > MainHero에 숫자로 올려둬야하는걸로 알고 있었는데 아녔나요?
![image](https://user-images.githubusercontent.com/38786000/214253792-d50e6828-554b-4f9f-84d7-f05765e5b607.png)

**Comment by DefineJH** [comment]
4294967295

**Comment by Koesob0508** [comment]
> 4294967295

오케이 확인

**Comment by DefineJH** [comment]
20으로 해도 되긴한데 그냥 찝찝해서..ㅋㅋ 추가될 수도 있구하니까 글케 씁시다
100부터는 또 적이구 하니

**Comment by DefineJH** [comment]
글고 @Koesob0508 이렇게 해야 멘션되는거 같음

**Comment by Koesob0508** [comment]
> 글고 @Koesob0508 이렇게 해야 멘션되는거 같음

@DefineJH  오... 새로 배웠다. 오키 그렇게 처리하도록 하겠습니다.
